In [72]:
import numpy as np

In [73]:
arr = np.random.randint(1,450,500)
arr

array([190, 387, 101, 284, 383, 332,  10, 110, 440,  78, 383, 273, 348,
       224,  36,  76, 103, 372, 147, 197,   1, 104, 255, 364, 274, 223,
       211, 389,   6, 265, 324, 310, 231,  60, 254, 303, 374, 319,  67,
       413, 134, 297,  24, 212, 176, 416, 360,  55, 115, 166, 199, 426,
       287, 127, 416, 240, 116, 287,   8, 149, 274, 168, 107, 439, 379,
       105, 250, 384, 111, 366, 330,  55,  76, 203,  68, 327, 403, 351,
       364, 104,  26, 300, 155,  78, 162, 197, 119,   6, 442, 311,  35,
       324, 247, 429,  58, 392,  10, 417, 163,  16, 277, 439, 315,   7,
       277, 267, 447, 114, 354, 385,  70,  86, 126, 178, 300,  97, 145,
       424,  34, 231, 180, 255, 303, 284, 398, 330,  78, 118, 432,  88,
       308, 111, 166, 193,  63, 230, 127, 239, 242, 196,  42, 270,  50,
        97, 393, 275, 299, 215, 328, 319, 190, 340,  75,  80, 273, 176,
       143, 120, 310, 148, 114,  43, 362, 129, 412,  97, 378,  34, 449,
        98, 434, 317, 163, 297, 166, 263,  22, 166, 196, 356, 37

In [74]:
count = 0
for i in arr:
    if i<100:
        count += 1
        print(i)

10
78
36
76
1
6
60
67
24
55
8
55
76
68
26
78
6
35
58
10
16
7
70
86
97
34
78
88
63
42
50
97
75
80
43
97
34
98
22
25
93
35
81
96
59
94
31
37
61
51
9
94
21
34
99
70
51
17
98
30
83
27
87
8
66
72
88
5
50
71
13
42
88
70
60
64
10
36
64
34
32
93
34
5
38
30
31
92
17
99
57
82
46
62
67
8
59
69
20
56
95
79
76
80
60
73
2
81
81
4


In [75]:
len(arr[arr<100])

110

In [76]:
# 2D Array


In [77]:
ls = [[1,2,3],
     [4,5,6],
     [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [78]:
type(ls)

list

In [79]:
arr2 = np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr2.ndim

2

In [81]:
arr2.shape

(3, 3)

In [82]:
arr2[0]

array([1, 2, 3])

In [83]:
arr2[2]

array([7, 8, 9])

In [84]:
arr2[0:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2[-1]

array([7, 8, 9])

In [86]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [87]:
arr2[0:3,0:1]

array([[1],
       [4],
       [7]])

In [88]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [89]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [90]:
arr2[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2[0: ,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [92]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [93]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [95]:
# 3D Array


In [96]:
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [97]:
ls = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
     [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
     [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
     [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [98]:
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [99]:
ls.shape

AttributeError: 'list' object has no attribute 'shape'

In [104]:
ls.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [108]:
arr3 = np.array(ls)
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [110]:
arr3.ndim

3

In [112]:
arr3.shape  # 4 tables, 3 row, 3 columns 

(4, 3, 3)

In [114]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [118]:
arr3[0:3]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [120]:
arr3[-3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
arr3[0: ,0:1, :]

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [130]:
arr3[: ,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [132]:
arr3[-4: ,-3:-2,-3:]

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [134]:
arr3[2:3,1: ,1:]

array([[[5, 6],
        [8, 9]]])

In [136]:
arr3[0:1,1: ,1:]

array([[[5, 6],
        [8, 9]]])

In [138]:
arr3[: , 1: ,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [142]:
arr3[:,-2:,-2:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [154]:
arr3[:,2:,-1::-1]

array([[[9, 8, 7]],

       [[9, 8, 7]],

       [[9, 8, 7]],

       [[9, 8, 7]]])

In [158]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
arr4 = arr3.ravel()
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
arr3.shape

(4, 3, 3)

In [170]:
arr3.reshape(36,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
arr.argmax()

np.int64(168)