In [35]:
import numpy as np
np.__version__



'2.0.1'

In [36]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [37]:
type(arr)

numpy.ndarray

In [38]:
arr.ndim

1

In [39]:
arr.size

7

In [40]:
len(arr)

7

In [41]:
arr.shape

(7,)

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr = np.array([25,10,20,30,40,50,60,25.2])
arr

array([25. , 10. , 20. , 30. , 40. , 50. , 60. , 25.2])

In [44]:
arr.dtype

dtype('float64')

In [45]:
arr = np.array([25,10,20,30,40,50,60,'hello'])
arr


array(['25', '10', '20', '30', '40', '50', '60', 'hello'], dtype='<U21')

In [46]:
arr.dtype

dtype('<U21')

In [47]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [48]:
arr[4:]

array([40, 50, 60])

In [49]:
arr[-3:-1]

array([40, 50])

In [50]:
arr[-1: -3: -1]

array([60, 50])

In [51]:
arr[-3:]

array([40, 50, 60])

In [52]:
arr + 5

array([30, 15, 25, 35, 45, 55, 65])

In [53]:
arr / 5


array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [54]:
min(arr)

np.int64(10)

In [55]:
max(arr)

np.int64(60)

In [56]:
sum(arr)

np.int64(235)

In [57]:
np.mean(arr)

np.float64(33.57142857142857)

In [58]:
np.median(arr)

np.float64(30.0)

In [59]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
import random

In [ ]:
np.random.randint(1,9)

In [ ]:
arr = np.random.randint(1,450,500)
arr

In [ ]:
import random ,string

In [ ]:
string.punctuation

In [ ]:
string.digits

In [ ]:
alpha = string.ascii_letters  +  string.digits

In [ ]:
random.choice