In [4]:
import numpy as np

In [6]:
arr = np.array([25, 10, 20, 30, 40, 50, 60])
arr.dtype  # dtype('int64')
arr.size   # 7
arr.shape  # (7,)
arr.ndim   # 1


1

In [8]:
arr = np.array([25, 10, 20, 30, 40, 50, 60, 25.2])
arr.dtype  # dtype('float64')
arr = np.array([25, 10, 20, 30, 40, 50, 60, 'hello'])
arr.dtype  # dtype('<U21')


dtype('<U21')

In [10]:
arr = np.array([25, 10, 20, 30, 40, 50, 60])
arr[4:]       # array([40, 50, 60])
arr[-3:-1]    # array([40, 50])
arr[-1:-3:-1] # array([60, 50])


array([60, 50])

In [12]:
arr + 5      # array([30, 15, 25, 35, 45, 55, 65])
arr / 5      # array([ 5., 2., 4., 6., 8., 10., 12.])


array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [14]:
np.min(arr)       # 10
np.max(arr)       # 60
np.sum(arr)       # 235
np.mean(arr)      # 33.57
np.median(arr)    # 30.0


np.float64(30.0)

In [16]:
arr = np.random.randint(1, 450, 500)
len(arr[arr < 100])  # 110 elements less than 100


115

In [18]:
ls = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(ls)
arr2.ndim   # 2
arr2.shape  # (3, 3)
arr2[1:3, 1:3]  # array([[5, 6], [8, 9]])


array([[5, 6],
       [8, 9]])